export enum BUTTON_ACTION {
    'ADD_PAYMENT' = 'ADD_PAYMENT',
    'PLACE_ORDER' = 'PLACE_ORDER'
}

export enum PAYMENT_OPTIONS {
    'FULL_PAYMENT' = 'FULL_PAYMENT',
    'PARTIAL_PAYMENT' = 'PARTIAL_PAYMENT',
    'PAY_LATER' = 'PAY_LATER'
}